site_name: Моя Документация
nav:
  - Главная: index.md
  - Лабы:
      - Лаб1: labs/lab1.md
      - Лаб2: labs/lab2.md
      - Лаб3: labs/lab3.md
  - Практики: practices/index.md

theme:
  name: material
