site_name: Моя Документация

nav:
  - Главная: index.md
  - Лабы:
      - Лаб1: labs/lab1.md
      - Лаб2:
          - task1: labs/lab2/task1.md
          - task2: labs/lab2/task2.md
      - Лаб3: labs/lab3/lab3.md

theme:
  name: material
